apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: monthly-backup
  namespace: $name
spec:
  schedule: "0 0 1 * *"
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: monthly-backup
              image: backup:latest
              imagePullPolicy: IfNotPresent
              command: ["python3", "backup.py"]
              env:
                - name: PERIODICITY
                  value: monthly